// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: recommendation.proto

package gengrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecommendationUseCase_GetRecommendations_FullMethodName = "/recommendation.RecommendationUseCase/GetRecommendations"
)

// RecommendationUseCaseClient is the client API for RecommendationUseCase service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecommendationUseCaseClient interface {
	GetRecommendations(ctx context.Context, in *RecommendationRequest, opts ...grpc.CallOption) (*RecommendationResponse, error)
}

type recommendationUseCaseClient struct {
	cc grpc.ClientConnInterface
}

func NewRecommendationUseCaseClient(cc grpc.ClientConnInterface) RecommendationUseCaseClient {
	return &recommendationUseCaseClient{cc}
}

func (c *recommendationUseCaseClient) GetRecommendations(ctx context.Context, in *RecommendationRequest, opts ...grpc.CallOption) (*RecommendationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendationResponse)
	err := c.cc.Invoke(ctx, RecommendationUseCase_GetRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecommendationUseCaseServer is the server API for RecommendationUseCase service.
// All implementations must embed UnimplementedRecommendationUseCaseServer
// for forward compatibility.
type RecommendationUseCaseServer interface {
	GetRecommendations(context.Context, *RecommendationRequest) (*RecommendationResponse, error)
	mustEmbedUnimplementedRecommendationUseCaseServer()
}

// UnimplementedRecommendationUseCaseServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecommendationUseCaseServer struct{}

func (UnimplementedRecommendationUseCaseServer) GetRecommendations(context.Context, *RecommendationRequest) (*RecommendationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecommendations not implemented")
}
func (UnimplementedRecommendationUseCaseServer) mustEmbedUnimplementedRecommendationUseCaseServer() {}
func (UnimplementedRecommendationUseCaseServer) testEmbeddedByValue()                               {}

// UnsafeRecommendationUseCaseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecommendationUseCaseServer will
// result in compilation errors.
type UnsafeRecommendationUseCaseServer interface {
	mustEmbedUnimplementedRecommendationUseCaseServer()
}

func RegisterRecommendationUseCaseServer(s grpc.ServiceRegistrar, srv RecommendationUseCaseServer) {
	// If the following call pancis, it indicates UnimplementedRecommendationUseCaseServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecommendationUseCase_ServiceDesc, srv)
}

func _RecommendationUseCase_GetRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationUseCaseServer).GetRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationUseCase_GetRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationUseCaseServer).GetRecommendations(ctx, req.(*RecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecommendationUseCase_ServiceDesc is the grpc.ServiceDesc for RecommendationUseCase service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecommendationUseCase_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recommendation.RecommendationUseCase",
	HandlerType: (*RecommendationUseCaseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRecommendations",
			Handler:    _RecommendationUseCase_GetRecommendations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recommendation.proto",
}
