with-expecter: true
dir: ./mocks
outpkg: mocks
issue-845-fix: true
packages:
  github.com/1Storm3/flibox-api/internal/controller:
      interfaces:
           AuthService:
           UserService:
           TokenService:

