version: '3.9'

services:
  prometheus:
    image: prom/prometheus:v2.37.9
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring_network
    depends_on:
      - flibox-api

  flibox-api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - monitoring_network
    env_file:
      - ../.env
    container_name: flibox-api

networks:
  monitoring_network:
    external: true
