global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'flibox-api'
    static_configs:
      - targets: [ 'flibox-api_prometheus_1:2020' ]